// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7l7PYB5Cw_h8mAlWGKH1riwWEgXhje0g',
    appId: '1:772420008111:web:b8869be10a30103a66bc5a',
    messagingSenderId: '772420008111',
    projectId: 'teckspark-barbearia',
    authDomain: 'teckspark-barbearia.firebaseapp.com',
    storageBucket: 'teckspark-barbearia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0EUFLJHhymzm-PYPsSfZ0Y0yWhUBr-Ek',
    appId: '1:772420008111:android:836b9c32d9b7967f66bc5a',
    messagingSenderId: '772420008111',
    projectId: 'teckspark-barbearia',
    storageBucket: 'teckspark-barbearia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzCtmLpYHTljCox4bylLu6vgBPtHiWWbs',
    appId: '1:772420008111:ios:f8cb5fc9a352740c66bc5a',
    messagingSenderId: '772420008111',
    projectId: 'teckspark-barbearia',
    storageBucket: 'teckspark-barbearia.firebasestorage.app',
    iosBundleId: 'com.example.teckSparkBarbearia',
  );
}
